kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  when:
    branch:
    - drone-it-up
  settings:
    repo: ocaml/rwo
    tags: base
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
