kind: pipeline
name: image

steps:
- name: base
  image: plugins/docker
  when:
    branch:
    - drone-it-up
  settings:
    repo: ocaml/rwo
    tags: base
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: build

steps:
- name: book
  image: ocaml/rwo:base
  pull: always
  environment:
    OPAMYES: 1
    OPAMJOBS: 32
    OPAMERRLOGLEN: 0
    OPAMCOLOR: always
  commands:
  - git -C /home/opam/opam-repository pull origin master && opam update -u
  - sudo chown -R opam .
  - opam pin add . -n
  - opam install rwo --deps-only
  - opam upgrade
  - opam exec -- make all
  - opam exec -- make test
  - opam exec -- make promote
  - git diff
